class Service {
  final String id;
  final String name;
  final String company;
  final String description;
  final double price;
  final String categoryId;
  final String image;
  final double rating;
  final double jarak;
  final int reviewCount;
  final String nomorwa;
  final int bookingCount;
  final List<String> images;
  final String address;
  final double latitude;
  final double longitude;

  final bool isFeatured;
  final bool isPopular;

  Service({
    required this.id,
    required this.name,
    required this.company,
    required this.description,
    required this.price,
    required this.categoryId,
    required this.image,
    required this.rating,
    required this.jarak,
    required this.reviewCount,
    required this.nomorwa,
    required this.bookingCount,
    required this.images,
    required this.address,
    required this.latitude,
    required this.longitude,
    this.isFeatured = false,
    this.isPopular = false,
  });

  factory Service.fromJson(Map<String, dynamic> json) {
    return Service(
      id: json['id'] as String,
      name: json['name'] as String,
      company: json['company'] as String,
      jarak: (json['jarak'] as num).toDouble(),
      description: json['description'] as String,
      price: (json['price'] as num).toDouble(),
      categoryId: json['categoryId'] as String,
      image: json['image'] as String,
      rating: (json['rating'] as num).toDouble(),
      reviewCount: json['reviewCount'] as int,
      nomorwa: json['nomorwa'] as String,
      bookingCount: json['bookingCount'] as int,
      images: (json['images'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      address: json['address'] as String,
      latitude: (json['latitude'] as num).toDouble(),
      longitude: (json['longitude'] as num).toDouble(),
      isFeatured: json['isFeatured'] as bool? ?? false,
      isPopular: json['isPopular'] as bool? ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'company': company,
      'description': description,
      'price': price,
      'categoryId': categoryId,
      'image': image,
      'rating': rating,
      'reviewCount': reviewCount,
      'nomorwa': nomorwa,
      'bookingCount': bookingCount,
      'images': images,
      'address': address,
      'latitude': latitude,
      'longitude': longitude,
      'isFeatured': isFeatured,
      'isPopular': isPopular,
    };
  }
}

// Example services for demo
List<Service> demoServices = [
  Service(
    id: '1',
    name: 'Muh. Syamsul Maarif',
    company: 'CV. Budi Mandiri',
    description:
        'Professional cleaning service to make your home spotless and fresh. Our team uses eco-friendly products and advanced cleaning techniques.',
    price: 120,
    categoryId: '1',
    jarak: 10,
    image: 'images/people.png',
    rating: 0.1,
    reviewCount: 245,
    nomorwa: "6287770093583",
    bookingCount: 1250,
    images: ['images/b.png', 'images/c.png', 'images/a.png'],
    address: "Batam Center, Kepulauan Riau",
    latitude: -4.0083753,
    longitude: 122.5577568,
    isFeatured: true,
    isPopular: true,
  ),
  Service(
    id: '2',
    name: 'Andisari',
    company: 'CV. Sari Jaya',
    description:
        'A thorough cleaning service for homes that need extra attention. Includes cleaning inside appliances, behind furniture, and detailed scrubbing.',
    price: 220,
    categoryId: '1',
    jarak: 5,
    image: 'images/people.png',
    rating: 4.9,
    reviewCount: 189,
    nomorwa: "6281804228935",
    bookingCount: 876,
    images: ['images/a.png', 'images/b.png', 'images/b.png'],
    address: "Batam Center, Kepulauan Riau",
    latitude: -4.000537,
    longitude: 122.5489654,
    isFeatured: true,
  ),
  Service(
    id: '3',
    name: 'Ibu Enda',
    company: 'CV. Anton Sejahtera',
    description:
        'Fast and reliable repair for any pipe leaks in your home. Our certified plumbers fix all types of pipe leaks to prevent water damage.',
    price: 90,
    categoryId: '2',
    jarak: 15,
    image: 'images/people.png',
    rating: 4.7,
    reviewCount: 156,
    nomorwa: "6287770093583",
    bookingCount: 735,
    images: ['images/a.png', 'images/b.png', 'images/b.png'],
    address: "Batam Center, Kepulauan Riau",
    latitude: -0.9471,
    longitude: 104.0305,
    isPopular: true,
  ),
  Service(
    id: '4',
    name: 'Pak samsudin',
    company: 'CV. Rolem Ipsum',
    description:
        'Complete bathroom installation service including fixtures, plumbing, and finishing. Transform your bathroom with our expert plumbers.',
    price: 580,
    categoryId: '2',
    jarak: 40,
    image: 'images/people.png',
    rating: 4.9,
    reviewCount: 122,
    nomorwa: "6281804228935",
    bookingCount: 450,
    images: ['images/a.png', 'images/b.png', 'images/b.png'],
    address: "Batam Center, Kepulauan Riau",
    latitude: -0.9471,
    longitude: 104.0305,
    isFeatured: true,
  ),
  Service(
    id: '5',
    name: 'Pak Bahar',
    company: 'CV. Anton Sejahtera',
    description:
        'Professional electrical wiring service for new installations or rewiring existing systems. All work meets safety codes and regulations.',
    price: 150,
    categoryId: '3',
    jarak: 30,
    image: 'images/people.png',
    rating: 4.8,
    reviewCount: 178,
    nomorwa: "6287770093583",
    bookingCount: 689,
    images: ['images/a.png', 'images/b.png', 'images/b.png'],
    address: "Batam Center, Kepulauan Riau",
    latitude: -0.9471,
    longitude: 104.0305,
    isFeatured: true,
    isPopular: true,
  ),
  Service(
    id: '6',
    name: 'Syamsudin',
    company: 'CV. Anton Sejahtera',
    description:
        'Transform your space with our professional painting services. We use high-quality paints and techniques for a perfect finish.',
    price: 320,
    categoryId: '4',
    jarak: 14,
    image: 'images/people.png',
    rating: 4.7,
    reviewCount: 205,
    nomorwa: "6281804228935",
    bookingCount: 920,
    images: ['images/a.png', 'images/b.png', 'images/b.png'],
    address: "Batam Center, Kepulauan Riau",
    latitude: -0.9471,
    longitude: 104.0305,
    isFeatured: true,
    isPopular: true,
  ),
  Service(
    id: '7',
    name: 'Muh. Arif',
    company: 'CV. Budi Mandiri',
    description:
        'Professional cleaning service to make your home spotless and fresh. Our team uses eco-friendly products and advanced cleaning techniques.',
    price: 120,
    categoryId: '1',
    jarak: 10,
    image: 'images/people.png',
    rating: 0.1,
    reviewCount: 245,
    nomorwa: "6287770093583",
    bookingCount: 1250,
    images: ['images/b.png', 'images/c.png', 'images/a.png'],
    address: "Batam Center, Kepulauan Riau",
    latitude: -0.9471,
    longitude: 104.0305,
    isFeatured: true,
    isPopular: true,
  ),
  Service(
    id: '8',
    name: 'Miftahul Jannah',
    company: 'CV. Greentech Studio',
    description:
        'Professional programming to make your home spotless and fresh. Our team uses eco-friendly products and advanced cleaning techniques.',
    price: 120,
    categoryId: '1',
    jarak: 20,
    image: 'images/people.png',
    rating: 5.0,
    reviewCount: 100,
    nomorwa: "6287770093583",
    bookingCount: 1250,
    images: ['images/b.png', 'images/c.png', 'images/a.png'],
    address: "Batam Center, Kepulauan Riau",
    latitude: -0.9471,
    longitude: 104.0305,
    isFeatured: true,
    isPopular: true,
  ),
  Service(
    id: '9',
    name: 'Robiatul adawiyah',
    company: 'CV. Budi Mandiri',
    description:
        'Professional cleaning service to make your home spotless and fresh. Our team uses eco-friendly products and advanced cleaning techniques.',
    price: 120,
    categoryId: '1',
    jarak: 10,
    image: 'images/people.png',
    rating: 0.1,
    reviewCount: 245,
    nomorwa: "6287770093583",
    bookingCount: 1250,
    images: ['images/b.png', 'images/c.png', 'images/a.png'],
    address: "Batam Center, Kepulauan Riau",
    latitude: -0.9471,
    longitude: 104.0305,
    isFeatured: true,
    isPopular: true,
  ),
  Service(
    id: '10',
    name: 'Nur Easi',
    company: 'CV. Budi Mandiri',
    description:
        'Professional cleaning service to make your home spotless and fresh. Our team uses eco-friendly products and advanced cleaning techniques.',
    price: 120,
    categoryId: '1',
    jarak: 10,
    image: 'images/people.png',
    rating: 0.1,
    reviewCount: 245,
    nomorwa: "6287770093583",
    bookingCount: 1250,
    images: ['images/b.png', 'images/c.png', 'images/a.png'],
    address: "Batam Center, Kepulauan Riau",
    latitude: -0.9471,
    longitude: 104.0305,
    isFeatured: true,
    isPopular: true,
  ),
  Service(
    id: '11',
    name: 'Satrio Pengetsu',
    company: 'CV. Budi Mandiri',
    description:
        'Professional cleaning service to make your home spotless and fresh. Our team uses eco-friendly products and advanced cleaning techniques.',
    price: 120,
    categoryId: '1',
    jarak: 10,
    image: 'images/people.png',
    rating: 0.1,
    reviewCount: 245,
    nomorwa: "6287770093583",
    bookingCount: 1250,
    images: ['images/b.png', 'images/c.png', 'images/a.png'],
    address: "Batam Center, Kepulauan Riau",
    latitude: -0.9471,
    longitude: 104.0305,
    isFeatured: true,
    isPopular: true,
  ),
];
